### ISSUE TITLE
 devin/fastlane/metadata/android/en-US/images/icon.png should be 512x512

### ISSUE THREAD

**Issue by eighthave** [ComputerScienceHouse/devin#4]
512x512 is the standard image size for app store icons, e.g. _ devin/fastlane/metadata/android/en-US/images/icon.png_  The current one is 8192x8192, and is too large to be included in f-droid.org

**Comment by Mstrodl** [comment]
Oops, I fixed this a while ago and never pushed it... :clown_face:
